[build]
  # Directory where the built files are stored
  publish = "dist"
  # Command to build the project
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html to support SPA routing
  from = "/*"
  to = "/index.html"
  status = 200